name: Furtravel
options:
  bundleIdPrefix: com.shimondeitel.pettravel
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  Furtravel:
    type: application
    platform: iOS
    sources:
      - path: Furtravel
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.pettravel
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: Furtravel/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  FurtravelTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: FurtravelTests
      - path: Furtravel.storekit
    dependencies:
      - target: Furtravel
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.pettravel.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  FurtravelUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: FurtravelUITests
    dependencies:
      - target: Furtravel
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.pettravel.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  Furtravel:
    build:
      targets:
        Furtravel: all
        FurtravelTests: [test]
        FurtravelUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: Furtravel.storekit
    test:
      config: Debug
      storeKitConfiguration: Furtravel.storekit
      targets:
        - FurtravelTests
        - FurtravelUITests
    archive:
      config: Release
